apiVersion: v1
kind: PersistentVolume
metadata:
  name: rate-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: rate-storage
  hostPath:
    path: /var/lib/containers/data/volumes/rate-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
